title: Salleh.Cloud
description: A tech blog on AI, ML, Cloud, Cybersecurity, and Blockchain.
show_excerpts: true

# Remove the theme line if present:
# theme: minima

# Add custom includes instead
plugins:
  - jekyll-feed
  - jekyll-seo-tag
