
show_excerpts: true
future: true

navigation:
  - title: Privacy
    url: /privacy/
  - title: ITIL FlashCard
    url: /itil-flashcards/

baseurl: "" # if you're using a custom domain like salleh.cloud

plugins:
  - jekyll-feed
  - jekyll-seo-tag
